### ISSUE TITLE
the .env file for storing webhook url doesnt work for me

### ISSUE THREAD

**Issue by Ryfters** [lulu5239/view-loggers#10]
the .env file for storing webhook url doesnt work for me(on both my version and this one), it just returns "Edge function has crashed", however it still works well when you just use const webhook = "webhook url"

**Comment by Zaid-maker** [comment]
`cp .env.example .env` then put your url and start the server if u are on local.
if u are deploying on Vercel there u just have to put your webhook url

**Comment by lulu5239** [comment]
There is indeed no `.env` file as I thought, you need to edit the environment variables from Vercel, in the project settings. *It isn't available on mobile, except when enabling desktop mode.*
![Screenshot_20240313_230553_Firefox](https://github.com/lulu5239/view-loggers/assets/32999164/537cdf5f-c20c-48c1-b03a-8b024b456628)
![Screenshot_20240313_230638_Firefox](https://github.com/lulu5239/view-loggers/assets/32999164/d2f70dc1-3793-49b2-8558-c24f37c2c7b8)

**Comment by lulu5239** [comment]
After editing the environment variable, we also need to make any change in the repository for Vercel to deploy the project with the updated webhook URL, or to re-deploy.
![Screenshot_20240313_234813_Firefox](https://github.com/lulu5239/view-loggers/assets/32999164/bfbba39c-0546-4267-ac8b-318ad6013a54)
![Screenshot_20240313_234838_Firefox](https://github.com/lulu5239/view-loggers/assets/32999164/791efe90-68dc-4221-af82-352a5a87ef98)
Maybe someone knows an easier way to do it.

**Comment by Ryfters** [comment]
thx, works now
