### ISSUE TITLE
everybody is leaking webhook urls

### ISSUE THREAD

**Issue by pk3zip** [lulu5239/view-loggers#2]
read title

**Comment by Zaid-maker** [comment]
> read title

Pretty easy fix tho i will make a Pull Request <3

**Comment by Zaid-maker** [comment]
U came from NTTS?

**Comment by Zaid-maker** [comment]
> > U came from NTTS?
> 
> yes

Found a fix opening PR

**Comment by tpglitch** [comment]
Gang this is why we dont use Next.js :facepalm:

**Comment by Zaid-maker** [comment]
Close this!

**Comment by lulu5239** [comment]
The pull request #3 should have fixed that issue. *I've tested it and it works.*
