### ISSUE TITLE
cant type in webhook text box, can only type in value text box ???

### ISSUE THREAD

**Issue by ghost** [lulu5239/view-loggers#8]

**Comment by Ryfters** [comment]
You need first to create the repo, then you will be able to enter the webhook

**Comment by obfuscated-loop** [comment]
The disabled `WEBHOOK_URL` input is the environment variable name being displayed on Vercel, you put the *value* of this variable inside of the **VALUE** input. The value being your Discord Webhook URL...

**Comment by lulu5239** [comment]
The "WEBHOOK_URL" text box is the name of the variable (if you understand what it means), where you need to paste the webhook URL is in the value box.
![Screenshot_20240313_225925_Firefox](https://github.com/lulu5239/view-loggers/assets/32999164/dd62edcd-a322-4e2b-b604-2558a2847de4)
